"""initial schema

Revision ID: 1d66188c092f
Revises: 
Create Date: 2026-08-26 13:02:30.584306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('agent', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    op.create_table('chamber_surveys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hospital_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('nameplate_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('daily_patients', sa.Integer(), nullable=False),
    sa.Column('avg_duration_min', sa.Integer(), nullable=False),
    sa.Column('consultation_fee_bdt', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('doctor_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('doctor_degrees', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('doctor_specializations', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("ocr_status IN ('pending', 'done', 'failed')", name='ck_surveys_ocr_status'),
    sa.CheckConstraint('(latitude IS NOT NULL AND longitude IS NOT NULL) OR (city IS NOT NULL AND district IS NOT NULL)', name='ck_surveys_location'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamber_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamber_surveys_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamber_surveys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamber_surveys_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamber_surveys_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamber_surveys_hospital_name'), ['hospital_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamber_surveys_user_id'), ['user_id'], unique=False)

    op.create_table('availability_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_slots_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_slots_time_order'),
    sa.ForeignKeyConstraint(['survey_id'], ['chamber_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_slots_survey_id'), ['survey_id'], unique=False)

    op.create_table('survey_phones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['chamber_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_phones_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_phones_survey_id'), ['survey_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_phones_survey_id'))
        batch_op.drop_index(batch_op.f('ix_survey_phones_phone'))

    op.drop_table('survey_phones')
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_slots_survey_id'))

    op.drop_table('availability_slots')
    with op.batch_alter_table('chamber_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_user_id'))
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_hospital_name'))
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_district'))
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_created_at'))
        batch_op.drop_index(batch_op.f('ix_chamber_surveys_city'))

    op.drop_table('chamber_surveys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_company'))

    op.drop_table('users')
    # ### end Alembic commands ###
