"""auth columns

Revision ID: ab09efceaf2b
Revises: 0001
Create Date: 2026-08-26 14:56:45.162323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_set_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            # server_default backfills the rows that already exist; without it
            # ADD COLUMN ... NOT NULL fails on a populated table.
            sa.Column('token_version', sa.Integer(), nullable=False, server_default='1')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')
        batch_op.drop_column('password_set_at')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
